"""initial schema

Revision ID: 5b1cd629f6ec
Revises: 
Create Date: 2026-03-17 02:55:03.701522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1cd629f6ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_token', sa.String(length=200), nullable=False),
    sa.Column('dealer_id', sa.String(length=36), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consent_items', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_logs_enrollment_token'), 'consent_logs', ['enrollment_token'], unique=False)
    op.create_table('mdm_ad_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slot_type', sa.String(length=30), nullable=False),
    sa.Column('floor_price_cpm', sa.Float(), nullable=False),
    sa.Column('targeting_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdm_ad_slots_slot_type'), 'mdm_ad_slots', ['slot_type'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('click_url', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['affiliate_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creatives_created_at'), 'creatives', ['created_at'], unique=False)
    op.create_table('mdm_impressions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=True),
    sa.Column('creative_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('enrollment_token', sa.String(length=64), nullable=True),
    sa.Column('dealer_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.Column('age_group', sa.String(length=10), nullable=True),
    sa.Column('cpm_price', sa.Float(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['mdm_ad_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdm_impressions_created_at'), 'mdm_impressions', ['created_at'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_creative_id'), 'mdm_impressions', ['creative_id'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_dealer_id'), 'mdm_impressions', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_device_id'), 'mdm_impressions', ['device_id'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_enrollment_token'), 'mdm_impressions', ['enrollment_token'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_served_at'), 'mdm_impressions', ['served_at'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_slot_id'), 'mdm_impressions', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mdm_impressions_slot_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_served_at'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_enrollment_token'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_device_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_dealer_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_creative_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_created_at'), table_name='mdm_impressions')
    op.drop_table('mdm_impressions')
    op.drop_index(op.f('ix_creatives_created_at'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_mdm_ad_slots_slot_type'), table_name='mdm_ad_slots')
    op.drop_table('mdm_ad_slots')
    op.drop_index(op.f('ix_consent_logs_enrollment_token'), table_name='consent_logs')
    op.drop_table('consent_logs')
    # ### end Alembic commands ###
