"""make impressions slot_id nullable

Revision ID: 8e0421d8e908
Revises: e1f2a3b4c5d6
Create Date: 2026-03-18 05:03:46.169239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e0421d8e908'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_profiles',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=20), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('mcc_mnc', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('storage_free_mb', sa.Integer(), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('cohort_label', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('dsp_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('take_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsp_configs_name'), 'dsp_configs', ['name'], unique=True)
    op.create_table('dsp_win_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('impression_id', sa.String(length=36), nullable=False),
    sa.Column('dsp_name', sa.String(length=100), nullable=False),
    sa.Column('bid_price_usd', sa.Float(), nullable=False),
    sa.Column('clearing_price_usd', sa.Float(), nullable=False),
    sa.Column('platform_revenue_jpy', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsp_win_logs_created_at'), 'dsp_win_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_dsp_win_logs_dsp_name'), 'dsp_win_logs', ['dsp_name'], unique=False)
    op.create_index(op.f('ix_dsp_win_logs_impression_id'), 'dsp_win_logs', ['impression_id'], unique=False)
    op.create_table('mdm_ad_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slot_type', sa.String(length=30), nullable=False),
    sa.Column('floor_price_cpm', sa.Float(), nullable=False),
    sa.Column('targeting_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdm_ad_slots_slot_type'), 'mdm_ad_slots', ['slot_type'], unique=False)
    op.create_table('ml_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('train_auc', sa.Float(), nullable=True),
    sa.Column('val_auc', sa.Float(), nullable=True),
    sa.Column('offline_ctr_lift', sa.Float(), nullable=True),
    sa.Column('tflite_size_mb', sa.Float(), nullable=True),
    sa.Column('tflite_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('time_slot_multipliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hour_start', sa.Integer(), nullable=False),
    sa.Column('hour_end', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_features',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('impression_count_30d', sa.Integer(), nullable=False),
    sa.Column('click_count_30d', sa.Integer(), nullable=False),
    sa.Column('ctr_30d', sa.Float(), nullable=False),
    sa.Column('avg_dwell_ms', sa.Float(), nullable=True),
    sa.Column('preferred_hour', sa.Integer(), nullable=True),
    sa.Column('dominant_dismiss_type', sa.String(length=20), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('feature_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_token', sa.String(length=64), nullable=True),
    sa.Column('dealer_id', sa.String(length=36), nullable=True),
    sa.Column('click_token', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['affiliate_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_campaign_id'), 'affiliate_clicks', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_click_token'), 'affiliate_clicks', ['click_token'], unique=True)
    op.create_index(op.f('ix_affiliate_clicks_clicked_at'), 'affiliate_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_dealer_id'), 'affiliate_clicks', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_enrollment_token'), 'affiliate_clicks', ['enrollment_token'], unique=False)
    op.create_table('affiliate_conversions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('click_token', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('revenue_jpy', sa.Float(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['affiliate_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_conversions_campaign_id'), 'affiliate_conversions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_affiliate_conversions_click_token'), 'affiliate_conversions', ['click_token'], unique=False)
    op.create_index(op.f('ix_affiliate_conversions_converted_at'), 'affiliate_conversions', ['converted_at'], unique=False)
    op.create_table('install_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('install_ts', sa.BigInteger(), nullable=False),
    sa.Column('apk_sha256', sa.String(length=64), nullable=True),
    sa.Column('billing_status', sa.String(length=20), nullable=False),
    sa.Column('postback_status', sa.String(length=20), nullable=False),
    sa.Column('postback_attempts', sa.Integer(), nullable=False),
    sa.Column('cpi_amount', sa.Float(), nullable=False),
    sa.Column('attribution_type', sa.String(length=20), nullable=False),
    sa.Column('vta_impression_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['affiliate_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_install_events_campaign_id'), 'install_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_install_events_device_id'), 'install_events', ['device_id'], unique=False)
    op.create_table('creative_experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slot_type', sa.String(length=50), nullable=False),
    sa.Column('control_creative_id', sa.String(length=36), nullable=False),
    sa.Column('variant_creative_id', sa.String(length=36), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['variant_creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mdm_impressions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=True),
    sa.Column('creative_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('enrollment_token', sa.String(length=64), nullable=True),
    sa.Column('dealer_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.Column('age_group', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cpm_price', sa.Float(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('video_event', sa.String(length=30), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['mdm_ad_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdm_impressions_created_at'), 'mdm_impressions', ['created_at'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_creative_id'), 'mdm_impressions', ['creative_id'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_dealer_id'), 'mdm_impressions', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_device_id'), 'mdm_impressions', ['device_id'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_enrollment_token'), 'mdm_impressions', ['enrollment_token'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_served_at'), 'mdm_impressions', ['served_at'], unique=False)
    op.create_index(op.f('ix_mdm_impressions_slot_id'), 'mdm_impressions', ['slot_id'], unique=False)
    op.create_table('postback_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('install_event_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['install_event_id'], ['install_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postback_logs_install_event_id'), 'postback_logs', ['install_event_id'], unique=False)
    op.alter_column('affiliate_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_affiliate_campaigns_agency_id'), 'affiliate_campaigns', ['agency_id'], unique=False)
    op.create_foreign_key(None, 'affiliate_campaigns', 'agencies', ['agency_id'], ['id'])
    op.alter_column('creatives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creatives_created_at'), 'creatives', ['created_at'], unique=False)
    op.create_foreign_key(None, 'creatives', 'affiliate_campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'dealers', 'agencies', ['agency_id'], ['id'])
    op.alter_column('impressions', 'slot_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'invoices', 'affiliate_campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'agencies', ['agency_id'], ['id'])
    op.alter_column('store_ad_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'store_ad_assignments', 'affiliate_campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'store_ad_assignments', 'dealers', ['dealer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_ad_assignments', type_='foreignkey')
    op.drop_constraint(None, 'store_ad_assignments', type_='foreignkey')
    op.alter_column('store_ad_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('impressions', 'slot_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'dealers', type_='foreignkey')
    op.drop_constraint(None, 'creatives', type_='foreignkey')
    op.drop_index(op.f('ix_creatives_created_at'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.alter_column('creatives', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'affiliate_campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_affiliate_campaigns_agency_id'), table_name='affiliate_campaigns')
    op.alter_column('affiliate_campaigns', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_postback_logs_install_event_id'), table_name='postback_logs')
    op.drop_table('postback_logs')
    op.drop_index(op.f('ix_mdm_impressions_slot_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_served_at'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_enrollment_token'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_device_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_dealer_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_creative_id'), table_name='mdm_impressions')
    op.drop_index(op.f('ix_mdm_impressions_created_at'), table_name='mdm_impressions')
    op.drop_table('mdm_impressions')
    op.drop_table('creative_experiments')
    op.drop_index(op.f('ix_install_events_device_id'), table_name='install_events')
    op.drop_index(op.f('ix_install_events_campaign_id'), table_name='install_events')
    op.drop_table('install_events')
    op.drop_index(op.f('ix_affiliate_conversions_converted_at'), table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_click_token'), table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_campaign_id'), table_name='affiliate_conversions')
    op.drop_table('affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_clicks_enrollment_token'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_dealer_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_clicked_at'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_click_token'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_campaign_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_table('user_features')
    op.drop_table('time_slot_multipliers')
    op.drop_table('ml_model_versions')
    op.drop_index(op.f('ix_mdm_ad_slots_slot_type'), table_name='mdm_ad_slots')
    op.drop_table('mdm_ad_slots')
    op.drop_index(op.f('ix_dsp_win_logs_impression_id'), table_name='dsp_win_logs')
    op.drop_index(op.f('ix_dsp_win_logs_dsp_name'), table_name='dsp_win_logs')
    op.drop_index(op.f('ix_dsp_win_logs_created_at'), table_name='dsp_win_logs')
    op.drop_table('dsp_win_logs')
    op.drop_index(op.f('ix_dsp_configs_name'), table_name='dsp_configs')
    op.drop_table('dsp_configs')
    op.drop_table('device_profiles')
    # ### end Alembic commands ###
